"""

เลือกโจทย์ โปรแกรมคำนวณเกรดจากคะแนน (A/B/C/D/F)
I : จำนวนคะแนน (score) 
P: sc < 50 = F sc >= 50 = D sc >= 60 = C sc >= 70 = B sc >= 80 = A
O : เกรดที่ได้
ตัวแปร : sc (score) , grade

"""
# -*- coding: utf-8 -*-
"""final26.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fcrMlY3ZmCAeOLO3VzpY0zs0iG_FqMkL
"""

print("สวัสดีครับ โปรแกรมคำนวณเกรดพร้อมแล้วครับ")
sc = int(input("กรอกคะแนน: "))

if sc >= 80:
    grade = "A"
elif sc >= 75:
    grade = "B+"
elif sc >= 70:
    grade = "B"
elif sc >= 65:
    grade = "C+"
elif sc >= 60:
    grade = "C"
elif sc >= 55:
    grade = "D+"
elif sc >= 50:
    grade = "D"
else:
    grade = "F"

print("เกรดที่ได้คือ:", grade)
print("เขียนโปรแกรมโดยณัฐพงศ์")
